### ISSUE TITLE
Issues with getting the GSL package installed

### ISSUE THREAD

**Issue by praveenkseshadri** [RobinHankin/gsl#20]
HI Robin,

We are trying to get the GSL package installed. We have RHEL 7.9 Enterprise and by default it installed gsl 1.15.

We are receiving the below error, Please let us know on how to get rid of this. We cannot change the system installed GSL version or can download anything outside of the RHEL standard repos  due to security issues

> install.packages("gsl")
Installing package into ‘/root/R/4.0.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.r-project.org/src/contrib/gsl_2.1-7.1.tar.gz'
Content type 'application/x-gzip' length 222357 bytes (217 KB)
==================================================
downloaded 217 KB

* installing *source* package ‘gsl’ ...
** package ‘gsl’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gsl-config... /bin/gsl-config
checking if GSL version >= 2.1... checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
gcc -std=gnu99 -I"/opt/R/4.0.5/lib/R/include" -DNDEBUG -I/usr/include -I.  -I/usr/local/include   -fpic  -g -O2  -c airy.c -o airy.o
gcc -std=gnu99 -I"/opt/R/4.0.5/lib/R/include" -DNDEBUG -I/usr/include -I.  -I/usr/local/include   -fpic  -g -O2  -c bessel.c -o bessel.o
gcc -std=gnu99 -I"/opt/R/4.0.5/lib/R/include" -DNDEBUG -I/usr/include -I.  -I/usr/local/include   -fpic  -g -O2  -c clausen.c -o clausen.o
gcc -std=gnu99 -I"/opt/R/4.0.5/lib/R/include" -DNDEBUG -I/usr/include -I.  -I/usr/local/include   -fpic  -g -O2  -c coulomb.c -o coulomb.o
gcc -std=gnu99 -I"/opt/R/4.0.5/lib/R/include" -DNDEBUG -I/usr/include -I.  -I/usr/local/include   -fpic  -g -O2  -c coupling.c -o coupling.o
gcc -std=gnu99 -I"/opt/R/4.0.5/lib/R/include" -DNDEBUG -I/usr/include -I.  -I/usr/local/include   -fpic  -g -O2  -c dawson.c -o dawson.o
gcc -std=gnu99 -I"/opt/R/4.0.5/lib/R/include" -DNDEBUG -I/usr/include -I.  -I/usr/local/include   -fpic  -g -O2  -c debye.c -o debye.o
gcc -std=gnu99 -I"/opt/R/4.0.5/lib/R/include" -DNDEBUG -I/usr/include -I.  -I/usr/local/include   -fpic  -g -O2  -c dilog.c -o dilog.o
gcc -std=gnu99 -I"/opt/R/4.0.5/lib/R/include" -DNDEBUG -I/usr/include -I.  -I/usr/local/include   -fpic  -g -O2  -c ellint.c -o ellint.o
ellint.c: In function ‘ellint_D_e’:
ellint.c:82:65: warning: passing argument 4 of ‘gsl_sf_ellint_D_e’ makes integer from pointer without a cast [-Wint-conversion]
   82 |     status[i] = gsl_sf_ellint_D_e(phi[i], k[i], sf_mode[*mode], &result) ;
      |                                                                 ^~~~~~~
      |                                                                 |
      |                                                                 gsl_sf_result * {aka struct gsl_sf_result_struct *}
In file included from ellint.c:1:
/usr/include/gsl/gsl_sf_ellint.h:84:66: note: expected ‘gsl_mode_t’ {aka ‘unsigned int’} but argument is of type ‘gsl_sf_result *’ {aka ‘struct gsl_sf_result_struct *’}
   84 | int gsl_sf_ellint_D_e(double phi, double k, double n, gsl_mode_t mode, gsl_sf_result * result);
      |                                                       ~~~~~~~~~~~^~~~
ellint.c:82:17: error: too few arguments to function ‘gsl_sf_ellint_D_e’
   82 |     status[i] = gsl_sf_ellint_D_e(phi[i], k[i], sf_mode[*mode], &result) ;
      |                 ^~~~~~~~~~~~~~~~~
In file included from ellint.c:1:
/usr/include/gsl/gsl_sf_ellint.h:84:5: note: declared here
   84 | int gsl_sf_ellint_D_e(double phi, double k, double n, gsl_mode_t mode, gsl_sf_result * result);
      |     ^~~~~~~~~~~~~~~~~
make: *** [ellint.o] Error 1
ERROR: compilation failed for package ‘gsl’
* removing ‘/root/R/4.0.5/gsl’

Best Regards,
Praveen

**Comment by markgalassi** [comment]
Dear Praveenk,

You did not giveus the output of printenv, but it seems clear that you are picking up your .h files from /usr/include/gsl instead of your local paths.

I would suggest either:

1. If you have root access, do a "sudo yum remove gsl gsl-devel" to remove the system library.

2. Make your C_INCLUDE_PATH point to your local source's include path before it goes to /usr/include.  You could try something like C_INCLUDE_PATH=`pwd`/something make

**Comment by praveenkseshadri** [comment]
HI Mark,

After I remove the package , I receive the below error. We do not have any user specific versions of gsl or can install any version of gsl higher than 1.15 as we only have to install the package from RHEL available repository


> install.packages("gsl")
Installing package into ‘/root/R/4.0.5’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/gsl_2.1-7.1.tar.gz'
Content type 'application/x-gzip' length 222357 bytes (217 KB)
==================================================
downloaded 217 KB

* installing *source* package ‘gsl’ ...
** package ‘gsl’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gsl-config... no
configure: error: gsl-config not found, is GSL installed?
ERROR: configuration failed for package ‘gsl’
* removing ‘/root/R/4.0.5/gsl’

The downloaded source packages are in
        ‘/rdata/R_temp/RtmpHRkQIj/downloaded_packages’
Warning message:
In install.packages("gsl") :
  installation of package ‘gsl’ had non-zero exit status
>



The version of RHEL  is 

Available Packages
gsl.i686                                                                                      1.15-13.el7                                                                                    rhel-7-server-rpms
gsl.x86_64                                                                                    1.15-13.el7                                                                                    rhel-7-server-rpms


Can you please advise on the workaround to circumvent these issues


Best Regards,
Praveen

**Comment by markgalassi** [comment]
> After I remove the package , I receive the below error. [...]

Oh, I had misunderstood and thought that you wanted to install gsl yourself from source.  I cannot imagine a security reason that would make gsl a problem, since it does no I/O or networking, but ...

If you have to use the system one then reinstall the system one, but you will need a version of the R code that is compatible with that.  Does the R installer allow you to specify an older gsl version?

**Comment by praveenkseshadri** [comment]
HI Mark,

I tried with older versions with the gsl package of 1.15 on the server

This is the error that I receive


> devtools::install_version("gsl", version = "2.1-1", repos = "http://cran.us.r-project.org")
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/gsl/gsl_2.1-1.tar.gz
Installing package into ‘/export/home/user1/R/4.0.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘gsl’ ...
** package ‘gsl’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gsl-config... /usr/bin/gsl-config
checking if GSL version >= 1.12... checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
configure: error: Need GSL version >= 1.12
ERROR: configuration failed for package ‘gsl’
* removing ‘/export/home/user1/R/4.0.5/gsl’
Warning message:
In i.p(...) :
  installation of package ‘/rdata/R_temp/RtmpSdcMyJ/remotes6bd159a9da54/gsl’ had non-zero exit status



gsl-config --version
1.15

**Comment by praveenkseshadri** [comment]
HI Mark,

Wanted to update, I was able to install one version below . We are yet to test this

 devtools::install_version("gsl", version = "1.9-10", repos = "http://cran.us.r-project.org")
