### ISSUE TITLE
Error installing gsl_2.1-6.

### ISSUE THREAD

**Issue by zji90** [RobinHankin/gsl#4]
I encountered the following issue trying to install the latest gsl_2.1-6 from CRAN. I have reviewed the previous post #1 and it seems that gsl_2.1-6 should be a fix to the issue, but I still have the same error. 
My gsl version is 2.5 and my system is CentOS 7. See below for the error message and sessionInfo.

Error message:

ellint.c:82:17: error: too few arguments to function ‘gsl_sf_ellint_D_e’
     status[i] = gsl_sf_ellint_D_e(phi[i], k[i], sf_mode[*mode], &result) ;
                 ^
In file included from ellint.c:1:0:
/software/centos7/usr/include/gsl/gsl_sf_ellint.h:84:5: note: declared here
 int gsl_sf_ellint_D_e(double phi, double k, double n, gsl_mode_t mode, gsl_sf_result * result);
     ^
make: *** [ellint.o] Error 1
ERROR: compilation failed for package ‘gsl’
* removing ‘/home-net/home-4/zji4@jhu.edu/R/x86_64-pc-linux-gnu-library/3.5/gcc/5.5/gsl’
Warning message:
In install.packages("gsl_2.1-6.tar.gz", repos = NULL, type = "source") :
  installation of package ‘gsl_2.1-6.tar.gz’ had non-zero exit status

SessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /software/apps/R/3.5.1/gcc/5.5.0/lib64/R/lib/libRblas.so
LAPACK: /software/apps/R/3.5.1/gcc/5.5.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1

**Comment by RobinHankin** [comment]
Hello zji90 (still learning github etiquette, please correct me if I get something wrong).  Note: "gsl" = the R package; "GSL" = Gnu Scientific Library by Galassi et al.

A few people have contacted me offline with this exact issue.  The error message is exactly what GSL version 1 would give with gsl_2.1-6,  so it looks to me that R is somehow picking up GSL version 1.  Note that gsl_2.1-6 compiles cleanly under all the architectures on CRAN:

  https://cran.r-project.org/web/checks/check_results_gsl.html

I'm looking right now at the GSL manual page for ```gsl_ellint_D_e()``` and gsl seems to have the correct sequence of arguments for GSL-2, which is strong evidence that R is not using GSL 2. In my experience, it is easy to install newer versions of GSL which for some reason are not picked up by R.

I'm not familiar with CentOS so I can't really advise on how to investigate this; let me know how you get on.  Best wishes, Robin

**Comment by zji90** [comment]
Thanks!
I think the problem is really the case that I am using an older GSL version. I checked the system and found that there are two versions of GSL installed, and R is by default picking the older version. Do you know how I can change the set up for R CMD INSTALL (probably something to do with --configure-args) so that R can pick up the later version? I already know the path to both old and new version.
Thanks!

**Comment by RobinHankin** [comment]
Unless you have a really good reason to keep the old version of GSL, I'd delete it and use the new one exclusively.  But if that is not an available solution,   I am not sure how to make R use the new version in preference to the old one, but there is probably an argument to ```configure``` (try ```./configure --help``` for some suggestions).  I am not an expert here, you could ask on the  R-devel mailing list (their first suggestion will be to ask me, so let them know that I'm passing on your question).  But really the Right Thing to do is to delete the old GSL and work with GSL-2. HTH, Robin

**Comment by zji90** [comment]
Thanks! I have resolved the issue.

**Comment by muschellij2** [comment]
I was getting this error as well in Travis.  It seems as though when using `trusty`, it has only GSL 1.16: https://launchpad.net/ubuntu/+source/gsl.  As per https://travis-ci.com/muschellij2/qMRI/jobs/206164590#L961, it seems as though it's installing that version.  The odd thing is that the autoconf indicates that GSL >= 2 is installed: https://travis-ci.com/muschellij2/qMRI/jobs/206164590#L961, but getting the same error here: https://travis-ci.com/muschellij2/qMRI/jobs/206164590#L4988 : 
```
ellint.c:82:5: error: too few arguments to function ‘gsl_sf_ellint_D_e’
```
