### ISSUE TITLE
Error when compiling gsl

### ISSUE THREAD

**Issue by jonathon-love** [RobinHankin/gsl#9]
hi,

i'm just having some difficulties compiling `gsl`, and was hoping for some advice on how to go about correcting the issue. i have `GSL` 2.6 installed, and you can see can see that `configure` finds `/app/bin/gsl-config` below. running `/app/bin/gsl-config --version` outputs `2.6`.

```
* installing *source* package ‘gsl’ ...
** package ‘gsl’ successfully unpacked and MD5 sums checked
checking for gsl-config... /app/bin/gsl-config
checking if GSL version >= 2.1... checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
configure: error: Need GSL version >= 1.16
ERROR: configuration failed for package ‘gsl’
```

any idea what the issue could be here?

with thanks

**Comment by RobinHankin** [comment]
hello Jonathon.  I'm not sure what is going on here, as GSL would seem to be installed correctly on your system.  Can you compile a "hello world"  C program such as `doc/examples/intro.c`?

**Comment by jonathon-love** [comment]
hi, thanks for the quick response.

i am able to build many R packages (including those that use native code) without issue.

with thanks

**Comment by jonathon-love** [comment]
hmm, let me do a bit more digging. it looks like the `include` headers are not where they should be.

with thanks

**Comment by skr5k** [comment]
i have exactly the same issue
```
:~$ gsl-config --version
2.4
```

but `install.packages("gsl")` gives
```
configure: error: Need GSL version >= 1.16
ERROR: configuration failed for package ‘gsl’
```

**Comment by sebidelamata** [comment]
Hi, I'm having this exact problem as well and was wondering if anyone found a solution?

**Comment by LiNk-NY** [comment]
Note. I am not getting this error and I am able to install `gsl` 
but, I have GSL version 2.5

```sh
$ /usr/bin/gsl-config --version
2.5
```
which triggers some conditional code in `gsl`

**Comment by PaulEloff** [comment]
Hi, I had this same issue today on Ubuntu 18.04, where I had GSL 2.4 installed, but I would get the "Need GSL version >= 1.16" error as well. After trying many **libgsl-dev** versions from many repos, the only solution that worked for me was the one suggested [here](https://askubuntu.com/questions/1364309/problems-getting-a-working-installation-of-gsl-2-6).

I don't think that the following is relevant, but my architecture involves running Ubuntu in WSL2 on a Windows 10 VM.
